### ISSUE TITLE
Cannot open the cost calculator anymore

### ISSUE THREAD

**Issue by ZachBora** [cem3cem3/CostCalculatorIssues#19]
Seems to be affecting just me, another person was able to open it.

Got this error in the Javascript
```CostCalculatorGraph.js:1 Uncaught RuntimeError: Aborted(). Build with -sASSERTIONS for more info.
    at abort (CostCalculatorGraph.js:1:24360)
    at _abort (CostCalculatorGraph.js:1:45480)
    at CostCalculatorGraph.wasm:0x1eb06
    at CostCalculatorGraph.wasm:0x33717
    at invoke_iiiii (CostCalculatorGraph.js:1:128988)
    at CostCalculatorGraph.wasm:0x69e0d
    at invoke_vi (CostCalculatorGraph.js:1:129770)
    at CostCalculatorGraph.wasm:0x13fd7
    at CostCalculatorGraph.wasm:0x44d3f
    at CostCalculatorGraph.js:1:64116
    at callUserCallback (CostCalculatorGraph.js:1:55083)
    at reportSuccess (CostCalculatorGraph.js:1:64053)
    at xhr.onload (CostCalculatorGraph.js:1:59613)
abort	@	CostCalculatorGraph.js:1
_abort	@	CostCalculatorGraph.js:1
$func906	@	CostCalculatorGraph.wasm:0x1eb06
$func1405	@	CostCalculatorGraph.wasm:0x33717
invoke_iiiii	@	CostCalculatorGraph.js:1
$func2251	@	CostCalculatorGraph.wasm:0x69e0d
invoke_vi	@	CostCalculatorGraph.js:1
$func670	@	CostCalculatorGraph.wasm:0x13fd7
$func1652	@	CostCalculatorGraph.wasm:0x44d3f
(anonymous)	@	CostCalculatorGraph.js:1
callUserCallback	@	CostCalculatorGraph.js:1
reportSuccess	@	CostCalculatorGraph.js:1
xhr.onload	@	CostCalculatorGraph.js:1
load (async)		
fetchXHR	@	CostCalculatorGraph.js:1
performUncachedXhr	@	CostCalculatorGraph.js:1
getRequest.onsuccess	@	CostCalculatorGraph.js:1
IndexedDB (async)		
fetchLoadCachedData	@	CostCalculatorGraph.js:1
_emscripten_start_fetch	@	CostCalculatorGraph.js:1
$func1835	@	CostCalculatorGraph.wasm:0x4c748
invoke_iii	@	CostCalculatorGraph.js:1
$Ea	@	CostCalculatorGraph.wasm:0x44465
Module._main	@	CostCalculatorGraph.js:1
callMain	@	CostCalculatorGraph.js:1
doRun	@	CostCalculatorGraph.js:1
run	@	CostCalculatorGraph.js:1
runCaller	@	CostCalculatorGraph.js:1
removeRunDependency	@	CostCalculatorGraph.js:1
receiveInstance	@	CostCalculatorGraph.js:1
receiveInstantiationResult	@	CostCalculatorGraph.js:1
Promise.then (async)		
(anonymous)	@	CostCalculatorGraph.js:1
Promise.then (async)		
instantiateAsync	@	CostCalculatorGraph.js:1
createWasm	@	CostCalculatorGraph.js:1
(anonymous)	@	CostCalculatorGraph.js:1
```

And then this error in the server log

![fatalerror](https://user-images.githubusercontent.com/1097596/183333749-f73c35d1-a4d6-4c7e-8d11-9e17c6ac27e8.png)

**Comment by ZachBora** [comment]
![fatalerror](https://user-images.githubusercontent.com/1097596/183333781-d12ad58d-721c-44c1-ae39-0865b6ca90b4.png)

**Comment by ZachBora** [comment]
Tried it again just now and it opened... Don't know what fixed it.

**Comment by ZachBora** [comment]
Problem happened again today. Opened in another browser and it opens but there's no graph since its a different browser.

**Comment by cem3cem3** [comment]
Thanks for the report! I haven't been able to find the reason as to what happened yet for the 9.6.2 release for the mod, but I will be looking into this further.
If/when you or someone else comes across this issue again, please let me know if the console also prints something like `fetch fail for request: [...]`.
