### ISSUE TITLE
Fails to load on v0.9.6.1 beta release-337

### ISSUE THREAD

**Issue by devdelimited** [cem3cem3/CostCalculatorIssues#20]
Loading a fresh server with the latest CostCalculator release results in a reflection error.

```
[21:15:34.096] [33] [ Warn] [Eco] Failed to get derived types for 'Eco.World.Blocks.Block' in assembly 'CostCalculator, Version=2.10.0.0, Culture=neutral, PublicKeyToken=null' (usually safe to ignore for third party assembly). Error message: Unable to load one or more of the requested types.

 
[21:15:34.172] [4] [ Info] [Eco] Server Initialization                             ... Finished in 14.775 sec
 
[21:15:34.172] [32] [Error] [Eco] Failed to start the server. Exception was Exception: ReflectionTypeLoadException
Message:Unable to load one or more of the requested types.

Source:System.Private.CoreLib

System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.

   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at Eco.Shared.Utils.ReflectionUtils.<>c.<GetFilteredAssemblyTypes>b__10_0(Assembly a)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at Eco.Core.Serialization.SimpleSerializer.InitializeSerializableTypes()
   at Eco.Core.Serialization.SimpleSerializer..cctor()
System.TypeLoadException
Outer Exceptions:
Exception has been thrown by the target of an invocation.
One or more errors occurred. (The type initializer for 'Eco.Core.Serialization.SimpleSerializer' threw an exception.)
The type initializer for 'Eco.Core.Serialization.SimpleSerializer' threw an exception.
```

**Comment by cem3cem3** [comment]
This is known. Unfortunately the Eco website is now a pre-compiled single page app, so it will take a while before I can release a new version of the mod that will work with Eco 9.6+.
