### ISSUE TITLE
Linux server crashing when installing Cost Calculator

### ISSUE THREAD

**Issue by AWL-Gaming** [cem3cem3/CostCalculatorIssues#21]
The mod is throwing an exception when installed on a Linux server. It works fine on Windows.

```
[08:53:46] Failed to start the server. Exception was Exception: TypeLoadException
Message:Could not load type 'vueComponent' from assembly 'ModUtils, Version=1.2.0.0, Culture=neutral, PublicKeyToken=null'.
Source:CostCalculator
System.TypeLoadException: Could not load type 'vueComponent' from assembly 'ModUtils, Version=1.2.0.0, Culture=neutral, PublicKeyToken=null'.
   at CostCalculator.CostCalculatorCore.setUpServerFiles(Assembly assembly)
   at CostCalculator.CostCalculatorCore..cctor()
Outer Exceptions:
One or more errors occurred. (The type initializer for 'CostCalculator.CostCalculatorCore' threw an exception.)
The type initializer for 'CostCalculator.CostCalculatorCore' threw an exception.
```

**Comment by cem3cem3** [comment]
Check for any old version of the Cost Calculator, as the current one only provides ModUtils version 1.3.0.0.

**Comment by AWL-Gaming** [comment]
Yes, tried the mod on a fresh Linux Install with no mods on. Made sure to also re-download the latest file from mod.io just in case.
Again, this works fine on Windows, just not Linux for some reason.

**Comment by cem3cem3** [comment]
That is very odd, because I develop entirely in linux and most of the time just assume it would work on windows too. Again, it seems like it somehow loads an outdated version of ModUtils, which should not exist within the current release of the mod.

Make sure that what you're putting on your linux server is definitely the new version of the `CostCalculator.dll`. To make sure, you can run `sha1sum ./CostCalculator.dll` on the dll file to check. It should print `9e2c5e0656b53a5392c3eb747c661606aaa4875b` for the most recent one.

A workaround you could add the `ModUtils.dll` to your mods directory directly. You'll find it here: https://github.com/cem3cem3/ModUtils/releases/tag/1.3.0.9.6.2R. Make sure that the server loads `ModUtils` first while it is loading mods and that should override whatever is provided internally by the CostCalculator mod.

**Comment by AWL-Gaming** [comment]
> That is very odd, because I develop entirely in linux and most of the time just assume it would work on windows too. Again, it seems like it somehow loads an outdated version of ModUtils, which should not exist within the current release of the mod.
> 
> Make sure that what you're putting on your linux server is definitely the new version of the `CostCalculator.dll`. To make sure, you can run `sha1sum ./CostCalculator.dll` on the dll file to check. It should print `9e2c5e0656b53a5392c3eb747c661606aaa4875b` for the most recent one.
> 
> A workaround you could add the `ModUtils.dll` to your mods directory directly. You'll find it here: https://github.com/cem3cem3/ModUtils/releases/tag/1.3.0.9.6.2R. Make sure that the server loads `ModUtils` first while it is loading mods and that should override whatever is provided internally by the CostCalculator mod.

Placing the ModUtils.dll file directly has worked, thank you!
