### ISSUE TITLE
[0.9.7.6] Crash on Launch

### ISSUE THREAD

**Issue by Dave247** [cem3cem3/CostCalculatorIssues#23]
As expected, the mod is broken on 9.7.X and needs to be updated. The following the is console output on a vanilla Windows x64 server,

```
[12:41:26.244] [15] [Error] [Eco] Failed to start the server. Exception was Exception: MissingMethodException
Message:Attempted to access a missing method.
Source:ModUtils

System.MissingMethodException: Attempted to access a missing method.
   at ModUtils.assemblyResolve.RegisterEmbeddedAssembly(Assembly assembly, String path, Version minVersion)
   at ModUtils.assemblyResolve.RegisterEmbeddedAssembly(Assembly assembly, String path)
   at CostCalculator.CostCalculatorCore.setupModUtils()
   at CostCalculator.CostCalculatorCore..cctor()
Outer Exceptions:
One or more errors occurred. (The type initializer for 'CostCalculator.CostCalculatorCore' threw an exception.)
The type initializer for 'CostCalculator.CostCalculatorCore' threw an exception.
 
[12:41:31.259] [15] [ Info] [Eco] Shutdown finished
 
[12:41:31.259] [15] [Error] [Eco] Errors report:
Failed to start the server. Exception was Exception: MissingMethodException
Message:Attempted to access a missing method.
Source:ModUtils

System.MissingMethodException: Attempted to access a missing method.
   at ModUtils.assemblyResolve.RegisterEmbeddedAssembly(Assembly assembly, String path, Version minVersion)
   at ModUtils.assemblyResolve.RegisterEmbeddedAssembly(Assembly assembly, String path)
   at CostCalculator.CostCalculatorCore.setupModUtils()
   at CostCalculator.CostCalculatorCore..cctor()
Outer Exceptions:
One or more errors occurred. (The type initializer for 'CostCalculator.CostCalculatorCore' threw an exception.)
The type initializer for 'CostCalculator.CostCalculatorCore' threw an exception.: 1
```

**Comment by cem3cem3** [comment]
Looks like the new Eco version switched to dotnet 7.0, which completely broke what little of harmony still worked. Unfortunately, trying to fix this is likely going to take a while.

**Comment by Dave247** [comment]
Yeah I saw other mods mention the upgrade to 7.0 also. Unstable that as your mod relied on Harmony, that it will take some time to rework the required parts to remove the dependency as that is something that is never easy to do.

**Comment by ZachBora** [comment]
Also wishing for this mod to work again, it was very useful!

**Comment by ruohki** [comment]
Any progress on this?

**Comment by cem3cem3** [comment]
Yes, I am still working on the mod, but don't expect anything pre 10.0.
This is because with 10.0, Eco will get direct web-page mod support, and thus this mod will no longer depend on 0Harmony and modUtils which are the main reasons for it not working at the moment.

**Comment by Dave247** [comment]
> 



> Yes, I am still working on the mod, but don't expect anything pre 10.0. This is because with 10.0, Eco will get direct web-page mod support, and thus this mod will no longer depend on 0Harmony and modUtils which are the main reasons for it not working at the moment.

Oh cool, with all the changes coming in update 10 that was one I hadn't heard about but should still be intrusting. Thanks for the update though,  with update 10 taking longer than everyone expected I know it might still be some time until we see anything from either front.

**Comment by ghost** [comment]
Hello, is there any information about the mod for version 10+?

**Comment by CraigWCooper** [comment]
@cem3cem3 I shall buy you a coffee when its you have updated it. Maybe a few.
